package whattimeisit;
import java.awt.*;
import javax.swing.*;

/**
 *
 * @author kadambari
 */
public class BasicForm extends javax.swing.JFrame {

    private Environment e;
        
    public BasicForm() {
        initComponents();
        
        e = new Environment();
        
        Component c = classNum.getEditor().getComponent(0);
        Component d = periodNum.getEditor().getComponent(0);
                
        //c.setForeground(new java.awt.Color(245,245,245));
        //c.setBackground(new java.awt.Color(36,47,65));
        //d.setForeground(new java.awt.Color(245,245,245));
       // d.setBackground(new java.awt.Color(36,47,65));
        
        int n = classNum.getComponentCount();
        for (int i=0; i<n; i++)
        {
            Component e = classNum.getComponent(i);
            Component f = periodNum.getComponent(i);
            if (e instanceof JButton)
            {
                e.setBackground(new java.awt.Color(36,47,65));
                f.setBackground(new java.awt.Color(36,47,65));
            }
        }  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        quote = new javax.swing.JLabel();
        icon = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        classLabel = new javax.swing.JLabel();
        greeting = new javax.swing.JLabel();
        periodLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        classNum = new javax.swing.JSpinner();
        periodNum = new javax.swing.JSpinner();
        submitButton = new javax.swing.JPanel();
        buttonText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(36, 47, 95));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(97, 212, 195));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        quote.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        quote.setForeground(new java.awt.Color(254, 254, 254));
        quote.setText("One who fails to plan , plans to fail");
        jPanel1.add(quote, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        icon.setForeground(new java.awt.Color(204, 204, 204));
        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/3.png"))); // NOI18N
        jPanel1.add(icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(254, 254, 254));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 280, 10));

        jSeparator3.setBackground(new java.awt.Color(254, 254, 254));
        jSeparator3.setForeground(new java.awt.Color(254, 254, 254));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 220, 30));

        jSeparator4.setForeground(new java.awt.Color(254, 254, 254));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 280, 10));

        jSeparator5.setForeground(new java.awt.Color(254, 254, 254));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 280, 10));

        jSeparator6.setBackground(new java.awt.Color(254, 254, 254));
        jSeparator6.setForeground(new java.awt.Color(254, 254, 254));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 220, 30));

        jSeparator7.setBackground(new java.awt.Color(254, 254, 254));
        jSeparator7.setForeground(new java.awt.Color(254, 254, 254));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 220, 30));

        jSeparator8.setBackground(new java.awt.Color(254, 254, 254));
        jSeparator8.setForeground(new java.awt.Color(254, 254, 254));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 220, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 450));

        jPanel3.setBackground(new java.awt.Color(36, 47, 65));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        classLabel.setForeground(new java.awt.Color(204, 204, 204));
        classLabel.setText("NUMBER OF CLASSES");
        jPanel3.add(classLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, 20));

        greeting.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        greeting.setForeground(new java.awt.Color(254, 254, 254));
        greeting.setText("Welcome User!");
        jPanel3.add(greeting, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        periodLabel.setForeground(new java.awt.Color(204, 204, 204));
        periodLabel.setText("NUMBER OF PERIODS");
        jPanel3.add(periodLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));

        jSeparator2.setBackground(new java.awt.Color(254, 254, 254));
        jSeparator2.setForeground(new java.awt.Color(254, 254, 254));
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 220, 30));

        jSeparator9.setBackground(new java.awt.Color(254, 254, 254));
        jSeparator9.setForeground(new java.awt.Color(254, 254, 254));
        jPanel3.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 220, 30));

        jSeparator10.setBackground(new java.awt.Color(254, 254, 254));
        jSeparator10.setForeground(new java.awt.Color(254, 254, 254));
        jPanel3.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 220, 30));

        jSeparator11.setBackground(new java.awt.Color(254, 254, 254));
        jSeparator11.setForeground(new java.awt.Color(254, 254, 254));
        jPanel3.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 220, 30));

        classNum.setModel(new javax.swing.SpinnerNumberModel(1, 1, 6, 1));
        classNum.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        classNum.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                catchClassValue(evt);
            }
        });
        jPanel3.add(classNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 220, -1));

        periodNum.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));
        periodNum.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        periodNum.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                catchPeriodValue(evt);
            }
        });
        jPanel3.add(periodNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 220, -1));

        submitButton.setBackground(new java.awt.Color(97, 212, 195));
        submitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                submitButtonMousePressed(evt);
            }
        });
        submitButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonText.setBackground(new java.awt.Color(254, 254, 254));
        buttonText.setForeground(new java.awt.Color(254, 254, 254));
        buttonText.setText("Submit");
        submitButton.add(buttonText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jPanel3.add(submitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 90, 40));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 360, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitButtonMousePressed
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ClassInfo(e).setVisible(true);                
            }
        });
        this.setVisible(false);
    }//GEN-LAST:event_submitButtonMousePressed

    private void catchClassValue(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_catchClassValue
        e.setClassNum((int)classNum.getValue());
    }//GEN-LAST:event_catchClassValue

    private void catchPeriodValue(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_catchPeriodValue
        e.setPeriodNum((int)periodNum.getValue());
    }//GEN-LAST:event_catchPeriodValue


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BasicForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BasicForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BasicForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BasicForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new BasicForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel buttonText;
    private javax.swing.JLabel classLabel;
    private javax.swing.JSpinner classNum;
    private javax.swing.JLabel greeting;
    private javax.swing.JLabel icon;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel periodLabel;
    private javax.swing.JSpinner periodNum;
    private javax.swing.JLabel quote;
    private javax.swing.JPanel submitButton;
    // End of variables declaration//GEN-END:variables
}
